<?php
use Yoti\ActivityDetails;

defined('_JEXEC') or die; // No direct access

require_once JPATH_SITE.'/components/com_yoticonnect/YotiConnectHelper.php';
require_once JPATH_SITE . '/components/com_yoticonnect/sdk/boot.php';
JPluginHelper::importPlugin('user');

/**
 * Class YotiConnectController
 *
 * @author Simon Tong <simon.tong@yoti.com>
 */
class YotiConnectController extends JControllerLegacy
{
    /**
     * @param bool $cachable
     * @param array $urlparams
     * @return JControllerLegacy
     */
    public function display($cachable = false, $urlparams = array())
    {
        $helper = new YotiConnectHelper;

        $redirect = (!empty($_GET['redirect'])) ? $_GET['redirect'] : 'index.php';
        switch ($this->input->get('task'))
        {
            case 'login':
                $helper->link();
                JFactory::getApplication()->redirect($redirect);
                break;

            case 'unlink':
                $helper->unlink();
                JFactory::getApplication()->redirect($redirect);
                break;

            case 'bin-file':
                $helper->binFile('selfie');
                exit;
                break;
        }

        return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
    }


}